services:
  mysql:
    build:
      context: ./sql
    container_name: mysql_container
    networks:
      - dock
    restart: always
    ports:
      - "3306:3306"
    volumes: 
      - mysql_volume:/var/lib/mysql
      - ./logs:/var/log/mysql

  wordpress:
    depends_on:
      - mysql
    build:
      context: ./wordpress
    container_name: wordpress_container
    networks:
      - dock
    restart: always
    ports:
      - "8080:80"
    volumes:
      - wordpress_volume:/var/www/html

networks:
  dock:

volumes:
  mysql_volume: {}
  wordpress_volume: {}